# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: MIT
"""Unit precondition for whether a blocking band has anything to replay.

Covers `MQC_CAS_UNI_115721`, inventoried in ``docs/design/consumer_ci.md``
section 4.

**A missing recording is an absence the floor cannot tell from a refusal.** A
provider declining a prompt is a measurement and is recorded as one; no
recording at all means the case was never asked, and a blocking band built on
that establishes nothing about anybody.

**It fails rather than being declarable.** A case that is not selected is never
recorded and never executed, so a tolerated gap is a permanent one: the project
owner's instruction of 2026-10-09, which refused the declaration file this
check was first drafted with (`consumer_ci.md` section 3.12.4).

A failure here is **not a model finding**, so the module carries no priority
marker, per the harness ``framework-rules.md`` section 3.3.
"""

# ------------------------------------------------------------- cases in here
# Generated by `tools/refresh_case_summaries.py`.
#
# TestMQCRecordingCoverage
#   115721  a_blocking_case_with_no_recording_is_reported
#   115722  a_recording_check_that_compares_nothing_is_reported
# ------------------------------------------------------------ end of cases

from pathlib import Path

import allure
import pytest

from cmn.replay_audit import missing_recordings

from tests.cases.graded_support import (
    engine_roster,
    repository_root,
    shipped_cases,
)

pytestmark = pytest.mark.unit


@allure.epic("AP-Model-QC")
@allure.feature("Recording coverage")
class TestMQCRecordingCoverage:
    """Every rostered engine can replay every case a blocking band selects."""

    @allure.story("A blocking band never rests on an absence")
    def MQC_CAS_UNI_115721_a_blocking_case_with_no_recording_is_reported(
        self,
    ) -> None:
        """Every P0 and P1 case has a recording for every rostered engine.

        **Every rostered engine, not the one under test.** The statement is
        about the corpus rather than about a gate: a gap present for one engine
        and silent for the others is the silence this check exists to end, and
        the project owner's sequence puts eliminating corpus gaps before
        measuring anything against a live agent.

        **A lower band is not held to this.** P2 to P4 are governed by a pass
        floor rather than by answering for everything, so a missing recording
        there costs coverage and does not block, and the band line already says
        `QC_HARNESS_FIXTURE_MISSING, no recorded response for this engine`.

        Design: ``consumer_ci.md`` section 3.12.4.

        Returns:
            None
        """
        root = repository_root()
        rostered = sorted(engine_roster())
        assert rostered, (
            "the roster names no engine, so this check would pass having "
            "compared the corpus against nothing"
        )

        cases = shipped_cases()
        blocking = [
            case_id for case_id, case in cases.items()
            if getattr(case.golden_rules, "priority", None) in (0, 1)
        ]
        assert blocking, (
            "the corpus declares no P0 or P1 case, so this check would pass "
            "having compared nothing"
        )

        problems = missing_recordings(root, rostered, cases)
        assert not problems, (
            f"{len(problems)} blocking-band case(s) have no recording, so a "
            f"band would skip rather than measure them and the gate would be "
            f"red on our gap rather than on a model. Record them with a live "
            f"run: " + "; ".join(problems)
        )

    @allure.story("The check compares something")
    def MQC_CAS_UNI_115722_a_recording_check_that_compares_nothing_is_reported(
        self, tmp_path: Path
    ) -> None:
        """An empty store reports every blocking case rather than passing.

        **A reader cannot tell a complete corpus from an unread one** unless
        the check says so when it finds nothing, which is the vacuity the
        instrument audit exists to prevent.

        Design: ``consumer_ci.md`` section 3.12.4.

        Returns:
            None
        """
        cases = shipped_cases()
        blocking = sum(
            1 for case in cases.values()
            if getattr(case.golden_rules, "priority", None) in (0, 1)
        )

        # AN EMPTY STORE REPORTS ONE ENTRY PER BLOCKING CASE, so a corpus with
        # no recordings at all cannot read as complete.
        empty = missing_recordings(tmp_path, ["gemini"], cases)
        assert len(empty) == blocking, (
            f"an empty store reported {len(empty)} of {blocking} blocking "
            f"cases, so the check does not see what it claims to compare"
        )

        # AND IT NAMES THE ENGINE AND THE CASE, because a count alone leaves a
        # reader with nothing to record.
        assert all("gemini" in entry for entry in empty), empty
        assert all("MQC_TASK_" in entry for entry in empty), empty

        # A ROSTER WITH NO ENGINE COMPARES NOTHING AND REPORTS NOTHING, which
        # is why the case above asserts the roster is populated first.
        assert not missing_recordings(tmp_path, [], cases)
