# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: MIT
"""Whether each engine is evaluated, named and reported on its own.

Covers ``MQC_CAS_UNI_115709``, inventoried in ``docs/design/consumer_ci.md``
section 4 and designed in sections 4.17 and 4.18.

**Extracted 2026-10-03**, when this subject took ``mqc_uni_workflows.py`` past
the thousand-line ceiling. The subject is one thing: these are the products of
different companies, so an aggregate over them answers no question anybody
asks, and the checks here are what keep the separation from quietly collapsing
back into one job.

A failure here is **not a model finding**, so the module carries no priority marker, per the
harness ``framework-rules.md`` section 3.3.
"""

# ------------------------------------------------------------- cases in here
# Generated by `tools/refresh_case_summaries.py`.
#
# TestMQCEngineAttribution
#   115709  a_graded_job_not_naming_its_engine_is_reported
#   115710  a_rostered_target_without_a_workflow_or_key_is_reported
# ------------------------------------------------------------ end of cases

from typing import Any

import allure
import pytest

from execution.adapters.registry import adapter_for

from tests.cases.graded_support import engine_roster
from tests.cases.workflow_support import (
    WORKFLOWS,
    graded_invocations,
    jobs,
    load,
)

pytestmark = pytest.mark.unit

# THE GATE FOR ONE TARGET, and the caller each target carries.
_GATE = "gate-target.yml"
_GATE_CALLER = "gate-{engine}.yml"
_LIVE = "evaluate-engine.yml"
_WEEKLY_CALLER = "evaluate-{engine}-weekly.yml"



def _rostered_engines() -> tuple[str, ...]:
    """Return the engines the roster carries, in the order it carries them.

    **Read from the harness, not restated here. Corrected 2026-10-05.** This
    was a tuple of three names whose comment claimed it was the roster, and it
    was the roster as it stood when the line was written: grok was rostered on
    2026-10-04 and nothing in this repository went red, because the check for a
    target without a workflow walked the hand-maintained copy. It could only
    fail for an engine somebody had already remembered to add.

    **A sequence rather than a set**, because the roster is ordered and the
    gate's calls chain in that order.

    Design: ``consumer_ci.md`` section 4.19.3.

    Returns:
        tuple[str, ...]: The rostered engine names.
    """
    return tuple(engine_roster())


def _target_problems(kind: str, pattern: str, called: str) -> list[str]:
    """Report a target that is not a workflow of its own.

    Args:
        kind (str): ``gate`` or ``weekly``, for the message.
        pattern (str): The caller filename, with an ``{engine}`` placeholder.
        called (str): The workflow a caller is expected to invoke.

    Returns:
        list[str]: One entry per problem.
    """
    problems: list[str] = []
    for engine in _rostered_engines():
        name = pattern.format(engine=engine)
        if not (WORKFLOWS / name).is_file():
            problems.append(
                f"{name} is absent, so {engine} has no {kind} of its own and "
                f"its conclusion would be another target's too"
            )
            continue
        loaded = load(name)
        calls = [
            job for job in jobs(loaded).values()
            if called in str(job.get("uses") or "")
        ]
        if not calls:
            problems.append(f"{name} does not call {called}")
        for job in calls:
            if str(((job.get("with") or {}).get("engine")) or "") != engine:
                problems.append(f"{name} calls {called} for another target")
        group = str(((loaded.get("concurrency") or {}).get("group")) or "")
        if engine not in group:
            problems.append(
                f"{name} has no concurrency group of its own, so one target's "
                f"run could supersede another's"
            )
    return problems


def _weekly_problems() -> list[str]:
    """Report a weekly caller carrying a schedule the design withholds.

    A live firing spends real money, and `consumer_ci.md` section 4.18.3 names
    what has to exist first: the known findings triaged, and a run that
    declines when this target was already evaluated in the window.

    Returns:
        list[str]: One entry per premature schedule.
    """
    problems: list[str] = []
    for engine in _rostered_engines():
        name = _WEEKLY_CALLER.format(engine=engine)
        if not (WORKFLOWS / name).is_file():
            continue
        triggers = load(name).get("on") or load(name).get(True) or {}
        if isinstance(triggers, dict) and "schedule" in triggers:
            problems.append(
                f"{name} carries a schedule, and section 4.18.3 withholds one "
                f"until the known findings are triaged and a run declines when "
                f"this target was already evaluated in the window"
            )
    return problems


def _band_problems(graded: dict[str, Any]) -> list[str]:
    """Report bands naming their engine literally or sharing an artifact name.

    Args:
        graded (dict): The loaded per-target gate.

    Returns:
        list[str]: One entry per problem.
    """
    problems: list[str] = []
    for job_name, job in jobs(graded).items():
        for body in graded_invocations(job):
            if "inputs.engine" not in body:
                problems.append(
                    f"{_GATE}:{job_name} names its engine literally rather "
                    f"than taking it from the call"
                )
        for step in job.get("steps") or []:
            if "upload-artifact" not in str(step.get("uses") or ""):
                continue
            name = str(((step.get("with") or {}).get("name")) or "")
            if name and "inputs.engine" not in name and graded_invocations(job):
                problems.append(
                    f"{_GATE}:{job_name} uploads {name!r}, which is not keyed "
                    f"by the engine, so two targets share a name"
                )
    return problems


def _credential_problems() -> list[str]:
    """Report a rostered engine whose credential the live workflow never offers.

    **A missing offer is quiet, which is why it needs a check.** A live leg
    whose credential is absent refuses at preflight, and section 4.17.2 is
    right to make that our configuration rather than a finding about a model.
    It is also indistinguishable from a skip nobody ordered: the caller exists,
    the run starts, and no result arrives.

    **The primary variable only.** An adapter may declare `ALSO_READS` for a
    second name its SDK resolves for itself, and the Gen AI client does; the
    environment needs one of them set, so requiring every alias would demand
    offers nothing reads.

    Design: ``consumer_ci.md`` section 4.19.3.

    Returns:
        list[str]: One entry per rostered engine with no offer.
    """
    body = (WORKFLOWS / _LIVE).read_text(encoding="utf-8")
    problems: list[str] = []
    for engine in _rostered_engines():
        variable = getattr(adapter_for(engine), "API_KEY_ENV", "")
        if not variable:
            problems.append(
                f"the {engine} adapter declares no credential variable, so "
                f"nothing here can establish that one is offered"
            )
            continue
        # THE ASSIGNMENT, NOT A MENTION, for the reason the harness's
        # `MQC_CMN_UNI_112520` gives: a name in a comment above an env block
        # reads as present and sets nothing.
        if f"{variable}:" not in body:
            problems.append(
                f"{_LIVE} offers no {variable}, so a live {engine} leg would "
                f"refuse at preflight and report our configuration rather than "
                f"a result"
            )
    return problems


@allure.epic("AP-Model-QC")
@allure.feature("Consumer CI")
class TestMQCEngineAttribution:
    """A target's result is its own, down to the workflow that produced it."""

    @allure.story("Every target is its own workflow")
    def MQC_CAS_UNI_115709_a_graded_job_not_naming_its_engine_is_reported(
        self,
    ) -> None:
        """Each target is its own workflow, named, and nothing aggregates.

        A target is an engine at a model version, and a graded failure is a
        finding about one of them. **A workflow run has a conclusion**, so
        three targets inside one gate produced a red run when two passed; the
        separation has to be at the workflow level, not the job level.

        Four properties:

        * the per-target gate takes its engine from an input, never a literal,
        * every rostered target has a gate caller **and** a weekly caller,
        * each caller names its target and keys its own concurrency group,
        * the artifacts a graded job uploads are keyed by the engine, because
          two targets sharing an artifact name is one name and the later
          upload wins.

        Design: ``consumer_ci.md`` sections 4.18 and 4.19.

        Returns:
            None
        """
        gate = load(_GATE)

        declared = (
            ((gate.get("on") or gate.get(True) or {}).get("workflow_call") or {})
            .get("inputs") or {}
        )
        assert "engine" in declared, (
            f"{_GATE} declares no engine input, so it cannot be per target"
        )
        assert jobs(gate), f"{_GATE} declares no jobs"

        problems = _band_problems(gate)
        problems.extend(_target_problems("gate", _GATE_CALLER, _GATE))
        problems.extend(_target_problems("weekly", _WEEKLY_CALLER, _LIVE))
        problems.extend(_weekly_problems())

        assert not problems, (
            "targets do not each have a workflow of their own: "
            + "; ".join(problems)
        )

    @allure.story("Rostering an engine is what adds it here")
    def MQC_CAS_UNI_115710_a_rostered_target_without_a_workflow_or_key_is_reported(
        self,
    ) -> None:
        """The roster is the list, and three things follow from an addition.

        **This exists because the previous check could not fail for the case
        it was written for.** grok was rostered on 2026-10-04, priced, and
        recorded; this repository kept gating three targets and stayed green,
        because the list of targets walked by `MQC_CAS_UNI_115709` was a tuple
        of three names whose comment claimed it was the roster.

        Asserted here, per rostered engine:

        * the roster read yields something, so a silent empty read cannot pass
          this vacuously,
        * each engine has a gate caller and a weekly caller, which
          `MQC_CAS_UNI_115709` checks over the same roster-derived list,
        * the live workflow offers the credential variable its adapter
          declares, which is the one of the three that fails quietly.

        **The secret's value is not this repository's business.** What is
        checked is that the wiring names it; the value lives in the `live`
        environment behind a required reviewer, and `credential_standard.md`
        governs the rest.

        Design: ``consumer_ci.md`` section 4.19.3.

        Returns:
            None
        """
        rostered = _rostered_engines()
        # A ROSTER THAT LOADED AS NOTHING would make every check above pass by
        # walking an empty sequence, which is the failure mode section 4.19.3
        # was written about in its hand-maintained form.
        assert len(rostered) >= 3, (
            f"the roster yielded {rostered}, so the installed harness is not "
            f"being read and every per-target check here would pass by walking "
            f"an empty list"
        )

        problems = _credential_problems()
        assert not problems, (
            "a rostered engine cannot be evaluated live with what the "
            "workflows offer: " + "; ".join(problems)
        )
