# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: MIT
"""Generate the per-case index a selector resolves a family or a tag through.

Specified by harness ``cmn_verdict_and_cli.md`` section 7.7.6.

**The grain is the point.** A matrix row is keyed by requirement and names
every case covering it, so resolving a family through the matrix selects the
whole row: ``--family source_fidelity`` returned 15 cases of which 6 graded it,
because the grounding requirements are formulated across two corpora
deliberately. The index is one row per case, so resolution is exact.

**It is also the tag vocabulary.** A tag lives on a task and nothing else could
refuse a tag no task carries, so a selector resolving through this index fails
on a typo instead of running nothing and reporting green.

**Generated, never authored.** An index of 69 cases maintained by hand drifts
from the first corpus edit, which is the argument that makes the matrix
families column derived as well.
"""

import argparse
import sys
from pathlib import Path
from typing import Final, Optional

from tests.cases.graded_support import case_rules_from_suite, shipped_corpus

_COLUMNS: Final[tuple[str, ...]] = ("case", "families", "tags")
_DEFAULT_OUT: Final[Path] = Path("docs/testing/case_index.csv")


def build(root: Path) -> list[dict[str, str]]:
    """Return one row per graded case, with its families and its task's tags.

    Args:
        root (Path): This repository's root.

    Returns:
        list[dict]: Rows in case order, each carrying the three columns.
        **A case whose rule declares no family is still listed**, with an empty
        cell, because omitting it would make the index disagree with the suite
        and `MQC_CAS_UNI_115414` is what holds the corpus to declaring one.
    """
    tasks, rules = shipped_corpus()
    families_by_rule = {entry.rule_id: entry.families for entry in rules}
    # SORTED, BECAUSE `tags` IS A FROZENSET. Iteration order varies between
    # processes, so an unsorted column would make this generated file differ
    # from itself on every run and never be current. Families keep their
    # declared order, where the first value is the primary one.
    tags_by_task = {entry.task_id: tuple(sorted(entry.tags or ())) for entry in tasks}

    rows: list[dict[str, str]] = []
    for case, (task_id, rule_id) in sorted(case_rules_from_suite(root).items()):
        rows.append({
            "case": case,
            "families": ";".join(families_by_rule.get(rule_id, ())),
            "tags": ";".join(tags_by_task.get(task_id, ())),
        })
    return rows


def render(rows: list[dict[str, str]]) -> str:
    """Return the index as the file holds it.

    Args:
        rows (list[dict]): The built rows.

    Returns:
        str: CSV with a leading comment, LF endings throughout.
    """
    lines = [
        "# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy",
        "# SPDX-License-Identifier: MIT",
        "# GENERATED BY tools/case_index.py. Do not edit.",
        "# Specified by harness cmn_verdict_and_cli.md section 7.7.6.",
        "# One row per case, which is the grain --family and --tag resolve at.",
        ",".join(_COLUMNS),
    ]
    lines.extend(
        ",".join(row[column] for column in _COLUMNS) for row in rows
    )
    return "\n".join(lines) + "\n"


def current(root: Path, out: Path) -> bool:
    """Report whether the written index matches what the corpus says now.

    Args:
        root (Path): This repository's root.
        out (Path): The index file.

    Returns:
        bool: True when they agree. **False where the file is absent**, which
        is a stale index rather than an acceptable one.
    """
    if not out.is_file():
        return False
    return out.read_text(encoding="utf-8") == render(build(root))


def main(argv: Optional[list[str]] = None) -> int:
    """Write the index, or report whether it is current.

    Returns:
        int: ``0`` when written or current, ``1`` when ``--check`` found it
        stale. **Exit 1 rather than rewriting under --check**, so a gate can
        report the staleness instead of hiding it.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=_DEFAULT_OUT)
    parser.add_argument(
        "--check", action="store_true",
        help="Report whether the index is current without writing it",
    )
    arguments = parser.parse_args(argv)
    root = Path(__file__).resolve().parents[1]

    if arguments.check:
        if current(root, arguments.out):
            print(f"{arguments.out} is current")
            return 0
        print(
            f"{arguments.out} disagrees with the corpus; regenerate it with "
            f"python -m tools.case_index",
            file=sys.stderr,
        )
        return 1

    rows = build(root)
    arguments.out.parent.mkdir(parents=True, exist_ok=True)
    arguments.out.write_text(render(rows), encoding="utf-8", newline="\n")

    families = len({name for row in rows for name in row["families"].split(";") if name})
    tags = len({name for row in rows for name in row["tags"].split(";") if name})
    print(
        f"wrote {arguments.out} with {len(rows)} case(s), "
        f"{families} famil(ies) and {tags} tag(s)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
