# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: MIT
"""Generate the code comprehension task file from the guarded excerpts.

Specified by ``docs/testing/model_evaluation_test_plan.md`` section 8.11.

**The excerpts are read, never retyped.** ``tests/fixtures/excerpts/`` holds
them and ``MQC_CAS_UNI_115100`` through ``115102`` guard them by parsing and
executing them. ``ContextDocument`` carries inline content and has no file
reference, so a task supplying an excerpt holds a second copy: generating that
copy from the fixture is what makes the two identical to begin with, and
``115005`` is what keeps them identical afterwards.

**This is the only way the task file is written.** ``115008`` compares the
shipped file to :func:`build` byte for byte, so a hand edit to it is reported
rather than silently lost at the next regeneration.

**Only the task file is generated.** The rule file beside it is hand-authored
and carries exemplars, reasoning and assertions that no generator produces, so
regeneration cannot clobber them.
"""

from pathlib import Path
from typing import Final

_ROOT: Final[Path] = Path(__file__).resolve().parents[1]
_EXCERPTS: Final[Path] = _ROOT / "tests" / "fixtures" / "excerpts"
_TARGET: Final[Path] = _ROOT / "data" / "tasks" / "code_comprehension.yaml"

# Content sits four levels in: task, key, block scalar, body.
_INDENT: Final[str] = "        "

_TABLE: Final[str] = (
    f"{_INDENT}Region,Orders,Revenue\n"
    f"{_INDENT}North,120,41200\n"
    f"{_INDENT}East,80,28700\n"
    f"{_INDENT}South,35,11400\n"
    f"{_INDENT}West,20,6100"
)

_SPEC: Final[str] = (
    f"{_INDENT}Release gate specification.\n"
    f"{_INDENT}A build is promoted when line coverage is at or above 82 percent.\n"
    f"{_INDENT}Builds below that figure are held for review."
)

_API: Final[str] = (
    f"{_INDENT}import httpx\n"
    f"\n"
    f"{_INDENT}def fetch_profile(client, user_id):\n"
    f'{_INDENT}    response = client.get(f"/users/{{user_id}}")\n'
    f"{_INDENT}    return response.json()"
)

_HEADER: Final[str] = '''# SPDX-FileCopyrightText: 2026 Aleksandr Polskiy
# SPDX-License-Identifier: MIT
# What the model is sent for the code comprehension family.
#
# GENERATED BY tools/generate_code_corpus.py. Do not edit this file by hand:
# MQC_CAS_UNI_115008 compares it to what the generator builds, and an edit here
# would be reported and then lost at the next regeneration.
#
# Specified by model_evaluation_test_plan.md sections 9.9 and 8.11.
#
# THE EXCERPTS ARE INLINED COPIES OF GUARDED FIXTURES. ContextDocument carries
# inline content and has no file reference, so these are a second copy of text
# that tests/fixtures/excerpts/ holds and 10401 to 10403 guard by parsing and
# executing it. Generating them from the fixtures makes the copies identical;
# MQC_CAS_UNI_115005 keeps them identical.
#
# MOST OF THIS FAMILY BRINGS NO REQUIREMENTS OF ITS OWN. Cases 30029 to 30037
# formulate GND_001, GND_002 and GND_004 in the code domain: a grounding
# requirement is domain-independent, and the point of a second formulation is
# that the behaviour survives a change of domain.
#
# CASES 30038 TO 30040 ARE THE EXCEPTION, added 2026-09-26 under MDL_DEF. They
# are not grounding: stating a source correctly and diagnosing why the source is
# wrong are different questions, and the settlement excerpt showed it. Its three
# asserted outcomes all follow from ONE cause, so a model listing them scored as
# though it had found the cause.
'''


def excerpt(name: str) -> str:
    """Return a guarded fixture indented for a YAML block scalar.

    Args:
        name (str): The fixture stem under ``tests/fixtures/excerpts``.

    Returns:
        str: The indented content. Blank lines are left empty rather than
        indented, so the file carries no trailing whitespace.
    """
    text = (_EXCERPTS / f"{name}.py.txt").read_text(encoding="utf-8")
    return "\n".join(
        _INDENT + line if line.strip() else "" for line in text.rstrip("\n").splitlines()
    )


# A TASK CARRIES ONE RULE NAMED AFTER IT, except where the prompt asks two
# separable things and the two are graded apart.
#
# `cod_settlement_causes` asks for the cause of each defect AND what the
# function should do instead. `MQC_EVL_EVAL_134109` grades the causes and
# `134110` the remedy. `MQC_RULE_cod_settlement_remedy` existed, carrying
# `constraint_ref: COD_STATE_CAUSE_AND_REMEDY`, and no task listed it, so
# `134110` asked for a pair `data/` never built and raised `KeyError` the first
# time it ran unmasked. `MQC_CAS_UNI_115011` now reports that without running.
_ADDITIONAL_RULES: Final[dict[str, tuple[str, ...]]] = {
    "cod_settlement_causes": ("MQC_RULE_cod_settlement_remedy",),
}


def _tasks() -> list[tuple[str, ...]]:
    """Return every task as its comment, identifiers, prompt and source.

    Returns:
        list[tuple]: One entry per task, in file order.
    """
    syntactic, logical, settle = (
        excerpt("top_scorers_syntactic"),
        excerpt("top_scorers_logical"),
        excerpt("settle_order_logical"),
    )
    return [
        ("# MQC_REQ_MDL_GND_0001, case 30029. No API absent from the snippet.",
         "cod_no_invented_api",
         "    Describe what the function below does, naming only the calls and\n"
         "    attributes that appear in it.",
         "COD_NO_INVENTED_API",
         "Name only calls and attributes that appear in the snippet",
         "requirement", "DOC_excerpt_api", "Snippet under review", _API,
         "[code_comprehension, fabrication]"),
        ("# MQC_REQ_MDL_GND_0001, case 30030. THE FUNCTION NAME INVITES THE FABRICATION.\n"
         "# It is called top_scorers and never sorts, so a summary calling it one\n"
         "# that returns the highest scorers is drawn from the name, not the code.",
         "cod_behaviour_not_intent",
         "    State what the function below returns when called with rows scoring\n"
         "    10, 90 and 50 and a limit of two. Describe what it does, not what it\n"
         "    appears intended to do.",
         "COD_BEHAVIOUR_NOT_INTENT",
         "Describe what the code does rather than what it appears intended to do",
         "requirement", "DOC_excerpt_top_scorers_logical", "Excerpt under review",
         logical, "[code_comprehension, intent]"),
        ("# MQC_REQ_MDL_GND_0001, case 30031. A tabular source, and the fabrication\n"
         "# target is a region the table does not carry.",
         "cod_no_added_row",
         "    List the regions in the table below with their order counts. Use only\n"
         "    the rows the table carries.",
         "COD_NO_ADDED_ROW", "Use only the rows the table carries",
         "requirement", "DOC_region_table", "Regional orders", _TABLE,
         "[code_comprehension, tabular, fabrication]"),
        ("# MQC_REQ_MDL_GND_0002, case 30032. Correct the syntax, preserve every literal.",
         "cod_preserves_literals",
         "    The excerpt below does not parse. Correct the syntax and return the\n"
         "    corrected function, changing nothing else: keep every literal, key and\n"
         "    argument exactly as written.",
         "COD_PRESERVE_LITERALS",
         "Keep every literal, key and argument exactly as written",
         "prohibition", "DOC_excerpt_top_scorers_syntactic", "Excerpt under review",
         syntactic, "[code_comprehension, syntactic, preservation]"),
        ("# MQC_REQ_MDL_GND_0002, case 30033. THE DISCOUNT TIERS MUST SURVIVE A REWRITE.\n"
         "# This is the discount-on-discount excerpt: the coupon is subtracted from\n"
         "# the discount figure rather than from the remaining total.",
         "cod_preserves_discount_tiers",
         "    The function below settles an order incorrectly. Explain what it\n"
         "    computes and what it should compute. Do not change the discount\n"
         "    percentages the module states.",
         "COD_PRESERVE_TIERS", "Do not change the stated discount percentages",
         "prohibition", "DOC_excerpt_settle_order", "Excerpt under review", settle,
         "[code_comprehension, logical, preservation]"),
        ("# MQC_REQ_MDL_GND_0002, case 30034. A stated threshold in a specification.",
         "cod_preserves_threshold",
         "    Summarise the release gate below in one sentence. State the coverage\n"
         "    threshold exactly as the specification states it.",
         "COD_PRESERVE_THRESHOLD", "State the coverage threshold exactly as specified",
         "prohibition", "DOC_release_gate_spec", "Release gate specification", _SPEC,
         "[code_comprehension, specification, preservation]"),
        ("# MQC_REQ_MDL_DEF_0001 and 0002, cases 30038 and 30039. CAUSE AND REMEDY,\n"
         "# which 30036 never asked for. That case lists the three OUTCOMES, and all\n"
         "# three follow from one cause, so a model naming them scores the same as\n"
         "# one that diagnosed the arithmetic.\n"
         "#\n"
         "# THE CALL SET IS WIDER HERE, DELIBERATELY. SAVE90 still settles below zero\n"
         "# once the inverted discount is corrected, which is what makes the missing\n"
         "# bound a SECOND defect rather than a symptom of the first. 30036's three\n"
         "# calls cannot separate them.",
         "cod_settlement_causes",
         "    The function below settles an order incorrectly. State the cause of\n"
         "    each defect rather than only what it returns, and say what the\n"
         "    function should do instead.\n"
         "\n"
         "    A discount is a percentage of the total. A coupon code is looked up\n"
         "    to a currency amount, so the two are different units.\n"
         "\n"
         "    It is called in production like this, against a 100 unit basket:\n"
         "\n"
         "    settle_order(\"standard\", 100, [\"SAVE30\"], {\"SAVE30\": 30})\n"
         "    settle_order(\"standard\", 100, [\"SAVE90\"], {\"SAVE90\": 90})\n"
         "    settle_order(\"standard\", 100, [\"NOPE\"], {\"SAVE30\": 30})\n"
         "    settle_order(\"standard\", 100, [\"SAVE20\", \"SAVE30\"],\n"
         "                 {\"SAVE20\": 20, \"SAVE30\": 30})",
         "COD_STATE_CAUSE_AND_REMEDY",
         "State the cause of each defect and what the function should do instead",
         "requirement", "DOC_excerpt_settle_order", "Excerpt under review", settle,
         "[code_comprehension, logical, diagnosis]"),
        ("# MQC_REQ_MDL_DEF_0003, case 30040. P4, AND A RECOMMENDATION RATHER THAN A\n"
         "# DEFECT. Nothing in the module bounds how long a code stays redeemable,\n"
         "# so every code issued works forever. That is a design weakness a good\n"
         "# review raises and not an error in what the code does, which is why it is\n"
         "# informational and cannot turn a run red on its own.",
         "cod_coupon_lifetime",
         "    The module below redeems coupon codes by looking them up. Nothing in\n"
         "    it limits how long a code stays redeemable, so every code ever issued\n"
         "    remains valid indefinitely.\n"
         "\n"
         "    Recommend how the design should bound a code's lifetime, and say what\n"
         "    the lookup would have to carry for that bound to be enforceable.",
         "COD_BOUND_COUPON_LIFETIME",
         "Recommend a bound on how long a coupon code stays redeemable",
         "requirement", "DOC_excerpt_settle_order", "Excerpt under review", settle,
         "[code_comprehension, logical, recommendation]"),
        ("# MQC_REQ_MDL_GND_0004, case 30035. The syntax error is at line 2, nowhere else.",
         "cod_syntax_location",
         "    The excerpt below does not parse. Say which line carries the error and\n"
         "    what the error is.",
         "COD_LOCATE_SYNTAX_ERROR", "Name the line carrying the syntax error",
         "requirement", "DOC_excerpt_top_scorers_syntactic", "Excerpt under review",
         syntactic, "[code_comprehension, syntactic, location]"),
        ("# MQC_REQ_MDL_GND_0004, case 30036. THE RECALL CASE. Three required outcomes,\n"
         "# graded conjunctively as assertions; two credited defects by rubric.\n"
         "#\n"
         "# ALL THREE CALLS ARE SUPPLIED, because an outcome the model was never\n"
         "# shown is not one it can be required to report. Each is settled by\n"
         "# execution: -10.0, 0.0 and a KeyError, against correct settlements of\n"
         "# 50.0, 60.0 and 50.0.",
         "cod_settlement_defects",
         "    Review the function below and list every defect you find. For each,\n"
         "    say what goes wrong and who is affected.\n"
         "\n"
         "    It is called in production like this, against a 100 unit basket:\n"
         "\n"
         '    settle_order("standard", 100, ["SAVE30"], {"SAVE30": 30})\n'
         '    settle_order("standard", 100, ["SAVE20"], {"SAVE20": 20})\n'
         '    settle_order("standard", 100, ["NOPE"], {"SAVE30": 30})',
         "COD_REPORT_EVERY_DEFECT", "List every defect the function carries",
         "requirement", "DOC_excerpt_settle_order", "Excerpt under review", settle,
         "[code_comprehension, recall, settlement]"),
        ("# MQC_REQ_MDL_GND_0004, case 30037. An aggregate derivable from the table, so a\n"
         "# wrong total is a verifiable falsehood rather than an opinion.",
         "cod_aggregate_from_table",
         "    State the total number of orders across all regions in the table\n"
         "    below, and the total revenue.",
         "COD_AGGREGATE_IS_DERIVED", "The totals must follow from the rows in the table",
         "requirement", "DOC_region_table", "Regional orders", _TABLE,
         "[code_comprehension, tabular, arithmetic]"),
    ]


def build() -> str:
    """Return the task file's contents.

    **Separate from writing**, so ``115008`` can compare the shipped file to the
    same code path an author runs. A check that rebuilt the expected output
    separately would assert that two copies of one algorithm agree, which is
    not the claim being made.

    Returns:
        str: The complete file, ending in a newline.
    """
    parts = [_HEADER]
    for (comment, stem, prompt, constraint_id, constraint_text, kind,
         document_id, title, content, tags) in _tasks():
        parts.append(
            f"\n{comment}\n"
            f"- task_id: MQC_TASK_{stem}\n"
            f"  rubric_ids: ["
            + ", ".join(
                (f"MQC_RULE_{stem}",) + _ADDITIONAL_RULES.get(stem, ())
            )
            + "]\n"
            f"  user_prompt: |\n{prompt}\n"
            f"  constraints:\n"
            f"    - constraint_id: {constraint_id}\n"
            f"      text: {constraint_text}\n"
            f"      kind: {kind}\n"
            f"  context_documents:\n"
            f"    - document_id: {document_id}\n"
            f"      title: {title}\n"
            f"      content: |\n{content}\n"
            f"  tags: {tags}\n"
        )
    return "".join(parts)


def main() -> None:
    """Write the task file.

    Returns:
        None
    """
    _TARGET.write_text(build(), encoding="utf-8", newline="\n")
    print(f"{_TARGET.relative_to(_ROOT).as_posix()}: {len(_tasks())} tasks")


if __name__ == "__main__":
    main()
